# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Lint ======================================================================
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.8
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix, --show-fixes]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.7.4"
    hooks:
      - id: prettier
        types_or: [yaml, html, css, scss, javascript, json]
  # - repo: https://github.com/jackdewinter/pymarkdown
  #   rev: v0.9.35
  #   hooks:
  #     - id: pymarkdown
  # Dependencies ==============================================================
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.26
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ["--output-file=requirements.txt", "--no-dev", "--quiet"]
  # Misc. =====================================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [html, svg]
      - id: trailing-whitespace
  # - repo: https://github.com/codespell-project/codespell
  #   rev: "v2.4.1"
  #   hooks:
  #     - id: codespell
  #       additional_dependencies:
  #         - tomli; python_version<'3.11'
  # Security ==================================================================
  # - repo: https://github.com/gitleaks/gitleaks
  #   rev: v8.24.2
  #   hooks:
  #     - id: gitleaks

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: false
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: monthly
